version: '3'
services:
  aerospike:
    image: aerospike/aerospike-server
    ports:
      - "3000:3000" # Client port
      - "3001:3001" # Service discovery port
      - "3002:3002" # Fabric port
      - "3003:3003" # Info port
    volumes:
      - aerospike-data:/opt/aerospike/data
      - ./aerospike.conf:/etc/aerospike/aerospike.conf

  clairvoyance:
    image: rashidmayes/clairvoyance
    depends_on:
      - aerospike
    ports:
      - "8080:8080" # Clairvoyance web UI port
    environment:
      - AEROSPIKE_HOST=aerospike
      - AEROSPIKE_PORT=3000

volumes:
  aerospike-data:
