version: '3.3'
services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    environment:
      SWAGGER_JSON: /mnt/swagger/openapi.json
    ports:
      - "3081:8080"
    volumes:
      - ./../api:/mnt/swagger
